# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 816b33707edb5b23f87b5ee8caf6d730306cc98b1228f7b74d17b59c514434ccb8640df4ee02e4cb5daa82cd723acf33c61218d43e2aff3f478f2763aba7ee43

test:
  secret_key_base: e64de419923dbae62327031fbe74eb73efc2ede8afb9f752798b3f643bbe420505ea2fe6f51bd156dfc696f495282e59d244ce8189eab1b7aaa383a57b1d3712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
